{% set version = "0.3.3" %}

package:
  name: pytmatrix
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytmatrix/pytmatrix-{{ version }}.tar.gz
  sha256: 34a1962a89c0f123ff815a05318abd09ad247613d3a2684747119a4cd67b9e5a

build:
  number: 0
  skip: true  # [win and py35]
  script:
    - python setup.py build --compiler=mingw32  # [win]
    - python setup.py install

requirements:
  build:
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - python
    - numpy         # [py27]
    - scipy
  run:
    - python
    - scipy
    - {{ pin_compatible('numpy') }}   # [py27]

test:
  imports:
    - pytmatrix
  commands:
    - python -c "from pytmatrix.test import test_tmatrix; test_tmatrix.run_tests()"

about:
  home: https://github.com/jleinonen/pytmatrix
  license: MIT
  license_file: LICENSE
  # license_file: LICENSE.txt
  summary: A Python code for computing the scattering properties of homogeneous nonspherical scatterers with the T-Matrix method.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - ocefpaf
