{% set version = "0.3.1" %}

package:
  name: pytmatrix
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytmatrix/pytmatrix-{{ version }}.zip
  sha256: 6ed1f2e1b0a32abd4a7649373ad3c0ba3862c385a9f8da360387177e6db0c6ae

build:
  number: 1001
  skip: True  # [win and py35]
  script:
    - python setup.py build --compiler=mingw32  # [win]
    - python setup.py install

requirements:
  build:
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - python
    - numpy         # [py27]
    - scipy
  run:
    - python
    - scipy
    - {{ pin_compatible('numpy') }}   # [py27]

test:
  imports:
    - pytmatrix
  commands:
    - python -c "from pytmatrix.test import test_tmatrix; test_tmatrix.run_tests()"
    - conda inspect linkages -p $PREFIX pytmatrix  # [not win]
    - conda inspect objects -p $PREFIX pytmatrix  # [osx]

about:
  home: https://github.com/jleinonen/pytmatrix
  license: MIT
  # license_file: LICENSE
  summary: A Python code for computing the scattering properties of homogeneous nonspherical scatterers with the T-Matrix method.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - ocefpaf
