{% set version = "0.3.0" %}

package:
  name: pytmatrix
  version: {{ version }}

source:
  fn: pytmatrix-{{ version }}.tar.gz
  url: https://github.com/jleinonen/pytmatrix/archive/{{ version }}.tar.gz
  sha256: 8733122ab547638fcf586e2069c231e61b411d283d42c4d0923258165f0aaa4b

build:
  number: 2
  skip: True  # [win and py35]
  script:
    - python setup.py build --compiler=mingw32  # [win]
    - python setup.py install

requirements:
  build:
    - python
    - numpy x.x
    - scipy <0.18.0
    - gcc  # [not win]
    - mingwpy  # [win]
  run:
    - python
    - numpy x.x
    - scipy <0.18.0
    # libquadmath
    - libgcc  # [linux]
    - libgfortran  # [osx]

test:
  imports:
    - pytmatrix
  commands:
    - python -c "from pytmatrix.test import test_tmatrix; test_tmatrix.run_tests()"
    - conda inspect linkages -n _test pytmatrix  # [not win]

about:
  home: https://github.com/jleinonen/pytmatrix
  license: MIT
  summary: A Python code for computing the scattering properties of homogeneous nonspherical scatterers with the T-Matrix method.

extra:
  recipe-maintainers:
    - kmuehlbauer
    - ocefpaf
