appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LwRkeDtsivzHYltqiAV1H8vh0cOlJHeughmmUeU5rhv1fPHt6HOYEj3YXtUj0wQkgYDn+jwTgSbDnTNUYTILyT56oxHltnBE9Av7ui/qVN+QRP41Qbv1ICAeWGf4/GZyCLRkOPimMPCAT2jbH0409vz2tYYvFsmpcZcCsY159CPDIumGf7l+M861BLRyiFcIISH8+xUU+/shwW4w4O5QtTQscKr0JsKMbI4GiD14t4RUroePZwuPZeoN/EqpsjOBcyTSnysNU8WVMihoZlt+V2ADwZNDnIrwKVjuMYBIBc9Cj1xvcuiTTKvRA5wdEXL0u0QepKs8zEoDOsc8qv2XyuEVvui5mPIRsrdF4wseUXZ+4HoCzFfc4O/JhuIqZ+kiXcEsUX10Y8N82hiF+QeNrD4S1UofzFxAGZokph5TSf21Smuk3p0ioVU9GGJTug74uMiGFBnia7yUaT1f3IFQkC6ifSwtnOlq0dJdLUOTOuEgmBSn5MQNJnrLlmRpGK4zu1KlMm1OrFtEZAo6yoOVGNIQpLwkgZqYq4GZO7QWe0momLAatiTY5aPdCX6tDIwpRacI0l0gFdQuXLLbJI19EzwXNEvhv9gLz3j3n81ZDI/jZL1otxyoi9c7/GYLNTKY+o/SWhyuGMMoomFpsTO7Rn4ZCYBI9tFp7HUNBdCVeLU=}
provider:
  win: azure
