travis:
  secure:
    BINSTAR_TOKEN: T6iwyc1Y2KRpo2t53GWG9IhBMXFPPDHQ03rHgMEcQPcovdg21AwZc765xLSVS7wYMMHH5agMd8BN84rFUDOTBxvqAUYRdQeljzr2nssVH6Na6qkZZIrH/IVKorE+v9ypQ1zh/kD31zhqJcOQKr4YaV9g/zpvlG+s6NFg77BoZ446rGAFo8s3GkFvRai7s+gPNbhp/PWtp14DSNlxUwoC1AZ13K13K8rfkQukXcZlQK7f+VLP2oyV5LPN+Mq+wM0TdFaMmWCS/DQJb8G3zU+5aHec43GupN0ID4s39WGDz79tvsA2EhTI/Y9TUpX0MEuhc7gxtoW2+4itRbfNSowbiGfL1E/vEubXFj/xNFDIYxEPRbhaEl5gjE3pFCD6ulK374M+jlq8sPLA8vBhQT50k8l7yUAN3OMSk7bv670kCgU76zSgS4aBD3O5x/ZPcQJrxDoph+qvO7FM2b2umkN1yRo0Cp25bKYWe00QQrRYinWDJ8DxMTldGTfvlcjy2uXsU/AKdn0QBqfvQyVvi0tZOZXCCWWwuaV4vm7trqc06kVrm6ioMszsG16tEF1pH9peZJEr8JN5sodbf+goBSreVue2pUZq0LF3TULk5QekV/8B1jfYj3W1C/NuyRT1Bqfake3p7RcvSSNU/bBZdcv6Ts4ApzsobX869HfmLUZqZ94=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
